name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # リポジトリのチェックアウト
    - name: Checkout repository 
      uses: actions/checkout@v4

    # Docker イメージのビルド
    - name: Build image
      run: docker build -f Dockerfile.test -t aqapp-test .

    # コンテナを実行
    - name: Run container
      run: docker run --rm aqapp-test


      