// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyBXd3m_sGjx_3j8XOtZzx7inSVBjjVVM',
    appId: '1:714159499544:web:ad2881f9a97296bd19566d',
    messagingSenderId: '714159499544',
    projectId: 'allowance-questboard',
    authDomain: 'allowance-questboard.firebaseapp.com',
    storageBucket: 'allowance-questboard.firebasestorage.app',
    measurementId: 'G-FNHRWEZ241',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh6gjsYeOTkjcstjAPlG38Gh0ewaldDmM',
    appId: '1:714159499544:android:77d81697ac7e27ee19566d',
    messagingSenderId: '714159499544',
    projectId: 'allowance-questboard',
    storageBucket: 'allowance-questboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHf52yc_9aiSAVxi8CnOE2DeZ7eIeCLKI',
    appId: '1:714159499544:ios:8f9f2a006f38c58f19566d',
    messagingSenderId: '714159499544',
    projectId: 'allowance-questboard',
    storageBucket: 'allowance-questboard.firebasestorage.app',
    iosBundleId: 'com.example.allowanceQuestboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHf52yc_9aiSAVxi8CnOE2DeZ7eIeCLKI',
    appId: '1:714159499544:ios:8f9f2a006f38c58f19566d',
    messagingSenderId: '714159499544',
    projectId: 'allowance-questboard',
    storageBucket: 'allowance-questboard.firebasestorage.app',
    iosBundleId: 'com.example.allowanceQuestboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyBXd3m_sGjx_3j8XOtZzx7inSVBjjVVM',
    appId: '1:714159499544:web:2e13a6e915d3ae1e19566d',
    messagingSenderId: '714159499544',
    projectId: 'allowance-questboard',
    authDomain: 'allowance-questboard.firebaseapp.com',
    storageBucket: 'allowance-questboard.firebasestorage.app',
    measurementId: 'G-4FDD6MTSQK',
  );
}
