name: allowance_questboard
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.0.2
  go_router: ^15.2.0
  badges: ^3.1.2
  mockito: ^5.4.4
  test: ^1.25.15
  flutter_riverpod: ^2.6.1
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  state_notifier: ^1.0.0
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.4.0
  supabase_flutter: ^2.9.1
  supabase_auth_ui: ^0.5.5
  logger: ^2.6.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  go_router_builder: ^3.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/

flutter_gen:
  output: lib/core/generated/
