@startuml "parent_mode"
left to right direction

class root {
    --
    ユーザ画面へ遷移()
    チーム画面へ遷移()
}

root --> タイムライン.collection
package "タイムライン" {
    class collection {
        select()
    }
}
タイムライン.collection --> 家族画面.single

root --> 通知画面.collection
package "通知画面" {
    class collection {}
    class single {}
    collection --> single: select()
}

package "家族画面" #LightPink {
    class single {
        名前@id
        アイコン
        説明文
        タイムライン
        フォロー
        フォロワー
        共有クエスト
        お気に入り登録された数
        --
        edit()
        follow()
        setting()
        child_list()
    }
    class edit {
        save()
    }
    class setting {
        --
        select()
        お小遣いテーブル設定()
        ランクごとの報酬テーブル設定()
        引き落とし申請設定()
        管理者設定()
    }
}
家族画面.single --> 家族画面.edit: edit()
家族画面.single --> 家族画面.setting: setting()

家族画面.setting --> 管理者設定.edit
package "管理者設定" #LightSlateGray {
    class edit {
        メールアドレス
        パスワード
        --
        save()
    }
}

家族画面.single --> メンバー画面.collection: child_list()
package "メンバー画面" #FloralWhite {
    class collection {
        select()
        new()
    }
    class single {
        id
        ユーザ名
        アイコン
        誕生日
        学年や職業 
        --
        ランク
        達成クエスト数
        合計報酬額
        定額報酬
        貯金
        今月の報酬金
        --
        edit()
        定期報酬()
        貯金()
        今月の報酬金()
    }
    class edit {
        save()
    }

    collection --> single: tap()
    collection --> edit: new()
    single --> edit: edit()
    }

メンバー画面.single --> お小遣い明細画面.collection: "今月の報酬金()"

package "お小遣い明細画面" #LightYellow {
    class collection {}
    class single {}
}
メンバー画面.single --> 貯金画面.collection: ""

package "貯金画面" #GreenYellow {
    class collection {
        select()
        引き落とし申請支払い()
        定期貯金額調整()
    }
}
貯金画面.collection o--> 引き落としリクエスト画面.single

package "引き落としリクエスト画面" #SkyBlue {
    class single {
        承認()
        否認()
    }
}
メンバー画面.single --> お小遣いテーブル画面.メンバー.single: ""

家族画面.setting --> お小遣いテーブル画面.テンプレート.collection
package "お小遣いテーブル画面" #GhostWhite {

    package "メンバー" #NavajoWhite {
        class single {}
        single --> edit
        class edit {}
    }

    package "テンプレート" #AntiqueWhite {

        class collection {}
        class single {}
        class edit {}
    }

}
メンバー画面.single --> ランクごとの報酬テーブル画面.メンバー.single: ""

家族画面.setting --> ランクごとの報酬テーブル画面.テンプレート.collection
package "ランクごとの報酬テーブル画面" #WhiteSmoke {
    package "メンバー" #NavajoWhite {
        class single {}
        single --> edit
        class edit {}
    }

    package "テンプレート" #AntiqueWhite {
        class collection {}
        class single {}
        class edit {}
    }
}

root --> クエスト画面.collection
package "クエスト画面" #AliceBlue {
    class collection {
        tap()
        new()
    }
    collection --> single: tap()
    collection --> edit: new()
    class single {
        edit()
    }
    single --> edit
    class edit {}
}

クエスト画面.collection --> クエスト分類.collection
package "クエスト分類" {
    class collection {
        new()
        edit()
        delete()
    }
}

家族画面.single --> フォロー画面.collection
package "フォロー画面" {
    class collection {
        select()
    }
}

クエスト画面.single --> コメント画面.collection

package "コメント画面" {
    class colleciton {}
}

package "報告画面" {
    class edit {}
}

通知画面.collection --> 意見箱画面.collection
package "意見箱画面" {
    class collection {}
    class edit {}

}

@enduml
