name: Flutter Test

on:
  # mainブランチにpushされたとき
  push:
    branches:
      - main
  # mainブランチにpull requestを送ったとき
  pull_request:
    branches:
      - main

jobs:
  flutter-test:
    # GitHub Actionsの実行環境のOSを指定
    runs-on: ubuntu-22.04

    steps:
      # リポジトリをGitHub Actionsの実行環境へコピー
      - name: Check out the code
        uses: actions/checkout@v2

      # Dockerのビルド環境のセットアップ
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Dockerイメージの作成とコンテナの実行
      - name: Build and run Docker container
        run: |
          docker build -f Dockerfile.test -t flutter-test .
          docker run flutter-test
